/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.hotel.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public class HotelPricePreview {
    @JsonProperty("hotelId")
    private String hotelid;
	@JsonProperty("displayPrice")
	private Double displayprice;

 	public void setDisplayprice(Double displayprice) {
		this.displayprice = displayprice;
	}

	public Double getDisplayprice() {
		return displayprice;
	}

 	public void setHotelid(String hotelid) {
		this.hotelid = hotelid;
	}

	public String getHotelid() {
		return hotelid;
	}

    @Override
    public String toString() {
        return "HotelPricePreview [hotelid=" + hotelid + ", displayprice=" + displayprice + "]";
    }

}