/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.hotel.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

public class HotelDetails {
	@JsonProperty("hotelId")
	private String hotelid;
    @JsonProperty("coordinates")
    private Coordinates coordinates;
    @JsonProperty("chainCode")
    private String chaincode;
    @JsonProperty("amenities")
    private List<String> amenities;
    @JsonProperty("address")
    private Address address;
    @JsonProperty("hotelName")
    private String hotelname;
    @JsonProperty("hotelDescription")
    private String hoteldescription;
    
 	public void setHotelid(String hotelid) {
		this.hotelid = hotelid;
	}

	public String getHotelid() {
		return hotelid;
	}

 	public void setHoteldescription(String hoteldescription) {
		this.hoteldescription = hoteldescription;
	}

	public String getHoteldescription() {
		return hoteldescription;
	}

 	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	public String getHotelname() {
		return hotelname;
	}

 	public void setAddress(Address address) {
		this.address = address;
	}

	public Address getAddress() {
		return address;
	}

 	public void setAmenities(List<String> amenities) {
		this.amenities = amenities;
	}

	public List<String> getAmenities() {
		return amenities;
	}

 	public void setChaincode(String chaincode) {
		this.chaincode = chaincode;
	}

	public String getChaincode() {
		return chaincode;
	}

 	public void setCoordinates(Coordinates coordinates) {
		this.coordinates = coordinates;
	}

	public Coordinates getCoordinates() {
		return coordinates;
	}

    @Override
    public String toString() {
        return "HotelDetails [hotelid=" + hotelid + ", coordinates=" + coordinates + ", chaincode=" + chaincode
                + ", amenities=" + amenities + ", address=" + address + ", hotelname=" + hotelname
                + ", hoteldescription=" + hoteldescription + "]";
    }

	
}